// A list of common locations and cities for search suggestions
export const locationSuggestions = [
  // Common location types
  { value: "home", label: "Home" },
  { value: "work", label: "Work" },

  // Major US cities
  { value: "new-york-ny", label: "New York, NY" },
  { value: "los-angeles-ca", label: "Los Angeles, CA" },
  { value: "chicago-il", label: "Chicago, IL" },
  { value: "houston-tx", label: "Houston, TX" },
  { value: "phoenix-az", label: "Phoenix, AZ" },
  { value: "philadelphia-pa", label: "Philadelphia, PA" },
  { value: "san-antonio-tx", label: "San Antonio, TX" },
  { value: "san-diego-ca", label: "San Diego, CA" },
  { value: "dallas-tx", label: "Dallas, TX" },
  { value: "san-jose-ca", label: "San Jose, CA" },
  { value: "austin-tx", label: "Austin, TX" },
  { value: "jacksonville-fl", label: "Jacksonville, FL" },
  { value: "san-francisco-ca", label: "San Francisco, CA" },
  { value: "columbus-oh", label: "Columbus, OH" },
  { value: "indianapolis-in", label: "Indianapolis, IN" },
  { value: "fort-worth-tx", label: "Fort Worth, TX" },
  { value: "charlotte-nc", label: "Charlotte, NC" },
  { value: "seattle-wa", label: "Seattle, WA" },
  { value: "denver-co", label: "Denver, CO" },
  { value: "washington-dc", label: "Washington, DC" },
  { value: "boston-ma", label: "Boston, MA" },
  { value: "nashville-tn", label: "Nashville, TN" },
  { value: "baltimore-md", label: "Baltimore, MD" },
  { value: "oklahoma-city-ok", label: "Oklahoma City, OK" },
  { value: "portland-or", label: "Portland, OR" },
  { value: "las-vegas-nv", label: "Las Vegas, NV" },
  { value: "milwaukee-wi", label: "Milwaukee, WI" },
  { value: "albuquerque-nm", label: "Albuquerque, NM" },
  { value: "tucson-az", label: "Tucson, AZ" },
  { value: "fresno-ca", label: "Fresno, CA" },
  { value: "sacramento-ca", label: "Sacramento, CA" },
  { value: "atlanta-ga", label: "Atlanta, GA" },
  { value: "kansas-city-mo", label: "Kansas City, MO" },
  { value: "miami-fl", label: "Miami, FL" },
  { value: "raleigh-nc", label: "Raleigh, NC" },
  { value: "omaha-ne", label: "Omaha, NE" },
  { value: "minneapolis-mn", label: "Minneapolis, MN" },
  { value: "cleveland-oh", label: "Cleveland, OH" },
  { value: "new-orleans-la", label: "New Orleans, LA" },
  { value: "honolulu-hi", label: "Honolulu, HI" },

  // Common search terms
  { value: "downtown", label: "Downtown" },
  { value: "uptown", label: "Uptown" },
  { value: "midtown", label: "Midtown" },
  { value: "suburb", label: "Suburb" },
  { value: "shopping-center", label: "Shopping Center" },
  { value: "mall", label: "Mall" },
  { value: "airport", label: "Airport" },
  { value: "university", label: "University" },
  { value: "college", label: "College" },
  { value: "hospital", label: "Hospital" },
  { value: "park", label: "Park" },
  { value: "beach", label: "Beach" },
]
